name: location
description: Cross-platform plugin for easy access to device's location in real-time.
version: 5.0.3
homepage: https://docs.page/Lyokone/flutterlocation
repository: https://github.com/Lyokone/flutterlocation
issue_tracker: https://github.com/Lyokone/flutterlocation/issues

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.lyokone.location
        pluginClass: LocationPlugin
      ios:
        pluginClass: LocationPlugin
      macos:
        pluginClass: LocationPlugin

dependencies:
  flutter:
    sdk: flutter
  location_platform_interface:
    git: https://github.com/ibrahimMahfuz/flutterlocation.git
    path: packages/location
    ref: 5.0.3-non-null-safety

dev_dependencies:
  async: ^2.5.0
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  leancode_lint: ^3.0.0
  mockito: ^5.0.0
